---
- name: add hdfs group
  group:
    state: present
    name: hdfs

- name: add hdfs user
  user:
    state: present
    name: hdfs
    system: yes
    createhome: no
    group: hdfs
    groups:
      - hdfs
      - hadoop

- name: configure hdfs-site
  template:
    src: hdfs-site.xml.j2
    dest: "{{ installation_dir }}/etc/hadoop/hdfs-site.xml"
