---
- name: add hdfs group
  group:
    state: present
    name: hdfs

- name: add hdfs user
  user:
    state: present
    name: hdfs
    system: yes
    createhome: no
    group: hdfs
    groups:
      - hdfs
      - hadoop

- name: create local fs namenode and datanode directories
  file:
    state: directory
    path: "{{ item }}"
    owner: hdfs
    group: hdfs
    mode: 0700
  with_items:
    - "{{ namenode_name_dir }}"
    - "{{ namenode_checkpoint_dir }}"
    - "{{ datanode_data_dir }}"

- name: configure hdfs-site
  template:
    src: hdfs-site.xml.j2
    dest: "{{ installation_dir }}/etc/hadoop/hdfs-site.xml"
