---
- name: add hadoop group
  group:
    state: present
    name: hadoop

- name: add hadoop user
  user:
    state: present
    name: hadoop
    group: hadoop
    system: yes

- name: install hadoop distribution
  unarchive:
    src: ../../../distributions/hadoop-3.0.0-beta1.tar.gz
    dest: /opt
    owner: hadoop
    group: hadoop
