---
- name: add hadoop group
  group:
    state: present
    name: hadoop

# temporarily commented out since it seems the copy is performed
# before the task is confirmed to be skip-able
# TODO fix that
# TODO change owner to... root?
#- name: install hadoop distribution
#  unarchive:
#    src: ../files/{{ distribution }}.tar.gz
#    dest: "{{ base_installation_dir }}"
#    owner: hadoop
#    group: hadoop

- name: append hadoop bin directory to system path
  lineinfile:
    state: present
    path: /etc/profile
    insertbefore: "export PATH"
    line: "PATH=\"${PATH}:{{ installation_dir }}/bin\""

- name: test PATH assignment value
  debug:
    msg: "PATH=\"${PATH}:{{ installation_dir }}/bin\""

- name: configure core-site
  template:
    src: core-site.xml.j2
    dest: "{{ installation_dir }}/etc/hadoop/core-site.xml"

# TODO set JAVA_HOME

# TODO modify the provided template to output 1 json object
#      (and add jq to the base-linux role)
- name: dump all variables
  template:
    src: dumpvars.j2
    dest: /home/pi/vars

