---
- hosts: all
  become: yes
  roles:
    - base-linux
    - java

- hosts: hadoop
  become: yes
  roles:
    - hadoop
    - hdfs

# TODO hdfs role will likely fall under hadoop,
#      and a namenode-specific role under namenodes
#- hosts: namenodes
#  become: yes
#  roles:
#    - hdfs
