---
- name: make system.d logfiles persistent
  file:
    state: directory
    path: /var/log/journal
    mode: 0700
    owner: root
    group: root

- name: install ntp
  apt:
    state: latest
    name: ntp

- name: set timezone to local timezone
  copy:
    dest: /etc/timezone
    content: "{{ timezone }}\n"
  notify:
    - point localtime to updated timezone
    - reconfigure timezone data
