---
- name: make system.d logfiles persistent
  file:
    state: directory
    path: /var/log/journal
    mode: 0700
    owner: root
    group: root

- name: set timezone to US Eastern
  lineinfile:
    state: present
    path: /etc/timezone
    line: America/New_York

- name: point localtime to US Eastern
  file:
    state: link
    name: /etc/localtime
    src: /usr/share/zoneinfo/America/New_York

- name: reconfigure timezone
  command: dpkg-reconfigure -f noninteractive tzdata

- name: install ntp
  apt:
    state: latest
    name: ntp
